image:
  file: dockerfiles/gitpod-base.Dockerfile

## Example is handled separately in GitPod for faster initialization.
tasks:
  # - name: Setup LF
  #   init: |
  #     bash ./.scripts/setup-lf.bash $RELEASE_BUILD
  #     gp sync-done setup-lf
  #   command: exit
  - name: Setup Example
    init: git clone https://github.com/kieler/models.git examples --branch master
    command: exit
  - name: Setup Java and node.js for user
    init: |
      bash -i ./.scripts/setup-user-env.bash
      gp sync-done setup-user-env
    command: exit
  - name: Notificaton
    command: |
      echo -e "\033[0;31mPlease wait while GitPod executes some finishing touch...... \033[0m"
      gp sync-await setup-user-env
      \. ~/.bashrc
      echo "Enjoy!"


vscode: 
  extensions:
    - kieler.keith-vscode
    - kieler.klighd-vscode
