image:
  file: dockerfiles/gitpod-base.Dockerfile

tasks:
  - name: Setup Example
    init: git clone https://github.com/kieler/models.git models --branch master
    command: exit

vscode: 
  extensions:
    - kieler.keith-vscode
    - kieler.klighd-vscode
